messages:
  help:
    - "&fПомощь по команде &6gps:"
    - "&6/gps &7x y z &f- установить компас на координаты. &7(100 100 100)"
    - "&6/gps cancel &f- сбросить настройку компаса."
  successful-input: "&fВаш компас настроен на координаты: &ex{x}, y{y}, z{z}"
  cancel: "&fЦель успешно сброшена!"
  only-player: "&fКоманда только для игроков!"
  only-numbers: "&fВведите числовое значение!"
  actionbar:
    way: "&fДо цели осталось: &6{blocks} блоков."
    place: "&fВы успешно достигли цели!"
distance: 15 # Расстояние до цели, при котором компас отключается.

